// Material-UI Core Components
export {
  Box,
  Card,
  CardContent,
  Typography,
  Avatar,
  Chip,
  Button,
  IconButton,
  Grid,
  Paper,
  LinearProgress,
  Divider,
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Rating,
  Fade,
  Slide,
  Zoom,
  useTheme,
  alpha,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow
} from '@mui/material';

// Material-UI Icons
export {
  Dashboard as DashboardIcon,
  PersonAdd as PersonAddIcon,
  Schedule as ScheduleIcon,
  History as HistoryIcon,
  Star as StarIcon,
  TrendingUp as TrendingUpIcon,
  AccessTime as AccessTimeIcon,
  VideoCall as VideoCallIcon,
  Message as MessageIcon,
  Check as CheckIcon,
  Close as CloseIcon,
  Add as AddIcon,
  Search as SearchIcon,
  Download as DownloadIcon,
  VerifiedUser as VerifiedIcon,
  EmojiEvents as ExpertIcon,
  FiberManualRecord as OnlineIcon,
  School as SchoolIcon,
  Psychology as PsychologyIcon,
  Assessment as AssessmentIcon,
  Group as GroupIcon,
  Event as EventIcon,
  Notifications as NotificationsIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Visibility as VisibilityIcon,
  ThumbUp as ThumbUpIcon,
  ThumbDown as ThumbDownIcon,
  Schedule as CalendarIcon,
  AssignmentTurnedIn as AssignmentIcon
} from '@mui/icons-material';
